name: CI

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use bazel
        run: ./bazelisk/bazelisk.py --version
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run tests
        run: ./bazelisk/bazelisk.py test :all
