name: CI

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bazelisk for Bazel builds
        uses: holvonix-open/setup-bazelisk@v0.6.0
      - name: Use bazel
        run: bazel --version
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run tests
        run: bazel test :all
