name: CI

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Use bazel
        run: bazel --version
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run tests
        run: bazel test :all
